#!/usr/bin/env bash

set -u

LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/apollo"
LOG="$LOG_DIR/gamescope.log"
mkdir -p "$LOG_DIR"

FPS="${APOLLO_CLIENT_FPS:-60}"
FPS="${FPS%.*}"

WIDTH="${APOLLO_CLIENT_WIDTH:-1280}"
HEIGHT="${APOLLO_CLIENT_HEIGHT:-800}"

{
  echo
  echo "--- $(date --iso-8601=seconds) gamescope launch ---"
  echo "WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-} XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-}"
  echo "APOLLO_CLIENT_WIDTH=$WIDTH APOLLO_CLIENT_HEIGHT=$HEIGHT APOLLO_CLIENT_FPS=$FPS"

  exec gamescope \
    --backend=wayland \
    -W "$WIDTH" \
    -H "$HEIGHT" \
    -r "$FPS" \
    -o "$FPS" \
    -f \
    -e \
    -F fsr \
    --fsr-sharpness 4 \
    -- steam -bigpicture
} >> "$LOG" 2>&1
